### ISSUE TITLE
play plugin not working

### ISSUE THREAD

**Issue by maklemenz** [evanchooly/sofia#6]
Things that are a problem in play:

* The 'core' is not in the plugin
* The code is written in Java7, which is not officially supported in play one. It has to be compatible with java 1.5 in play 1.2.5 (since this is officially supported) or compatible to 1.6, which is supported, too.
* The freemarker dependency seems to be missing
* The classes are not in the classpath after including the module

I will fork the project and change some things to bring it to work properly under play one. Hope I can help a little bit.

**Comment by evanchooly** [comment]
no more need for a play plugin
